### ISSUE TITLE
New pages show state as a modified instead draft. 

### ISSUE THREAD

**Issue by ishannz** [silverstripe/silverstripe-versioned-snapshots#21]
Version SilverSripe: 4.4.3
silverstripe-versioned-snapshots Version: latest(master)

Steps to reproduce:
1. Create a new page.
2. You will see state of the page is modified instead draft.

![Screen Shot 2019-09-11 at 10 19 17 AM](https://user-images.githubusercontent.com/20032948/64654544-b25dc100-d47d-11e9-829f-790d2e15e2b5.png)

**Comment by blueo** [comment]
@ishannz I don't think this module displays the site tree (it alters the history viewer in the history tab). It might not be the right one for this issue (happy to be corrected if I'm missing something).

**Comment by ishannz** [comment]
@blueo  when I remove this module from the project, start to work as expected. (showing the draft instead Modified), not sure what causes this issue yet.
