### ISSUE TITLE
reconcileOwnershipChanges() chokes on unversioned has_ones

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-versioned-snapshots#36]
I have a snapshotted data object with has_ones to Member.

I get errors of the from
```
Message: InvalidArgumentException: Class SilverStripe\Security\Member does not have the SilverStripe\Versioned\Versioned extension
```

Notable call stack is

```
#0 SilverStripe\Snapshots\SnapshotPublishable::get_published_version_number called at [/vendor/silverstripe/versioned-snapshots/src/SnapshotPublishable.php:194]
#1 SilverStripe\Snapshots\SnapshotPublishable::getSnapshotsSinceLastPublish called at [:0]
#4 SilverStripe\View\ViewableData::__call called at [/vendor/silverstripe/versioned-snapshots/src/SnapshotPublishable.php:592]
#5 SilverStripe\Snapshots\SnapshotPublishable::reconcileOwnershipChanges called at [:0]
#8 SilverStripe\View\ViewableData::__call called at [/vendor/silverstripe/versioned-snapshots/src/Snapshot.php:322]
#9 SilverStripe\Snapshots\Snapshot::createSnapshot called 
```

It appears as though reconcileOwnershipChanges() treats every altered has_one as a "change in ownership" and assumes (by calling getSnapshotsSinceLastPublish) that the object is versioned.

reconcileOwnershipChanges() should have a path where unversioned objects are handled in a simpler way. I _believe_ that the snapshot migration can be skipped entirely for such objects, but I would want to confirm with @unclecheese.

**Comment by unclecheese** [comment]
Oh lucky you, you've stumbled upon the most complex corner of this module. 😬

This is one of those things I knew would break at some point, given the correct test conditions, so thanks for flushing it out.

I think right here, you want a `hasExtension()` check for Versioned:

https://github.com/silverstripe/silverstripe-versioned-snapshots/blob/master/src/SnapshotPublishable.php#L547

And we should definitely add a new unit test for this condition.

**Comment by unclecheese** [comment]
Actually, I'm just thinking about it some more, and I think this may be way overengineered. Why is it assuming every hasOne is an "owner?" So If I change the has_one category field on my blog entry, it's going to try to kick off a snapshot migration? That doesn't seem right.

I wonder if we need to make some kind of allow list for what relationships are considered "owners".. Maybe that hasOne list needs to be cross referenced with `ownedBy`, or `findOwners`?

**Comment by sminnee** [comment]
Yeah I thought we already had owned-by already implemented in versioned?

**Comment by sminnee** [comment]
It looks like `Versioned::findOwners()` provides this information.

**Comment by unclecheese** [comment]
I believe @scott1702 is experiencing the same issue. Scott, can you test this PR and see if it resolves it for you? If so, that's two data points and we can merge. :)

**Comment by sminnee** [comment]
Collaboration!
