### ISSUE TITLE
No author is recorded for a snapshot

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-versioned-snapshots#41]
In various situations the `AuthorID` field of a Snapshot is left at default (`0`) inaccurately recording who has made a snapshot (e.g. published a page and all child elements).

This issue is opened on the snapshots module rather than the snapshots-admin module as it relates to database information, rather than an Author Name displaying in the CMS.

However, related, it was found and caused confusion in part with trying to lightly debug why https://github.com/silverstripe/silverstripe-versioned-snapshot-admin/issues/50 is happening. I thought the lack of AuthorID might be the reason the Author's name was missing in the UI. It does not appear to be this way however.

## Reproduce

- Create project, require snapshot(-admin), dev/build, etc.
- `/admin/pages/edit/show/2`
- _Type_ "Changes" into the `Content` TinyMCE
- _Click_ `Save & Publish`
- _Click_ `History` tab 👀 One entry, by you, just now. All seems correct.
- _View_ database `VersionedSnapshot` table. 👀 `AuthorID` is `0`

![image](https://user-images.githubusercontent.com/778003/115181336-ce324a00-a12b-11eb-9321-f5b8b67ffd78.png)

I note that the absence of the AuthorID does not seem to impact the function of the history log in this case

![image](https://user-images.githubusercontent.com/778003/115181461-1e111100-a12c-11eb-8069-2f296a0309a3.png)

Perhaps I'm misunderstanding the purpose of this field. In more advanced tests I have noted it is correctly inputted to the database _sometimes_. This is not because I am Default Admin as this is still a valid user with an ID.

**Comment by unclecheese** [comment]
Have not been able to replicate this. Will need more details on reproducing.

**Comment by NightJar** [comment]
Sorry, I got distracted in struggling to reproduce another issue in the history domain.

This issue is opened on the snapshots module rather than the snapshots-admin module as it relates to database information, rather than an Author Name displaying in the CMS.

However, related, it was found and caused confusion in part with trying to lightly debug why https://github.com/silverstripe/silverstripe-versioned-snapshot-admin/issues/50 is happening. I thought the lack of AuthorID might be the reason the Author's name was missing in the UI. It does not appear to be this way however.

## Reproduce

- Create project, require snapshot(-admin), dev/build, etc.
- `/admin/pages/edit/show/2`
- _Type_ "Changes" into the `Content` TinyMCE
- _Click_ `Save & Publish`
- _Click_ `History` tab 👀 One entry, by you, just now. All seems correct.
- _View_ database `VersionedSnapshot` table. 👀 `AuthorID` is `0`

![image](https://user-images.githubusercontent.com/778003/115181336-ce324a00-a12b-11eb-9321-f5b8b67ffd78.png)

I note that the absence of the AuthorID does not seem to impact the function of the history log in this case

![image](https://user-images.githubusercontent.com/778003/115181461-1e111100-a12c-11eb-8069-2f296a0309a3.png)

Perhaps I'm misunderstanding the purpose of this field. In more advanced tests I have noted it is correctly inputted to the database _sometimes_. This is not because I am Default Admin as this is still a valid user with an ID.

**Comment by unclecheese** [comment]
Good catch. This should be resolved by https://github.com/silverstripe/silverstripe-versioned-snapshots/commit/f60c2693bf94f24c3214d1d8b9ffb8fb5dbd020e

**Comment by NightJar** [comment]
This has been resolved - although I'm testing with `unclecheese:pulls/master/will-workflow-food` it also contains f60c269
